# Generated Documentation Config
springdoc:
  swagger-ui:
    path: /docs

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spec_demo
    username: dev-ninja
    password: ujac8ozJExiHFfcTNPd6
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  application:
    name: aaj-spring-jpa-spec-demo
server:
  http2:
    enabled: true
  port: ${PORT:8080}
  error:
    include-message: always